# name: Laravel
# on: [push, pull_request]
# jobs:
#   laravel-tests:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: ./app
#     steps:
#       - uses: actions/checkout@v4

#       - name: Setup PHP
#         uses: shivammathur/setup-php@v2
#         with:
#           php-version: '8.3'
#           # extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
#           extensions: sqlite
#           coverage: none

#       - name: Install dependencies
#         # run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
#         run: composer install --no-interaction --prefer-dist --optimize-autoloader

#       - name: Create environment file..
#         run: php -r "file_exists('.env') || copy('.env.example', '.env');"

#       - name: Generate application key
#         run: php artisan key:generate

#       - name: Directory Permissions
#         run: chmod -R 777 storage bootstrap/cache

#       - name: Create Database
#         run: |
#           mkdir -p database
#           touch database/database.sqlite

#       - name: Migrate Database
#         env:
#           DB_CONNECTION: sqlite
#           DB_DATABASE: database/database.sqlite
#         run: php artisan migrate

#       - name: Execute tests
#         run: php artisan test
name: Tests

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: sqlite
          tools: composer:v2
          coverage: xdebug

      - name: Create environment file..
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-interaction --no-progress --prefer-dist --optimize-autoloader

      - name: Tests
        run: ./vendor/bin/pest
